### ISSUE TITLE
Regarding sunset of bintray

### ISSUE THREAD

**Issue by henrikgei** [jfrog/setup-jfrog-cli#34]
Hello,

This repo calls bintray to download the cli in this file: https://github.com/jfrog/setup-jfrog-cli/blob/master/src/utils.ts

According to this blog entry Bintray goes away soon, right?
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

So my question is: 
Will there be an update to this repo to deal with this? Or where is the new recommended location to download the cli if we want to patch this ourselves?

**Comment by SherryChengAwsTacFuji** [comment]
I have also been seeing 403 error this morning.

**Comment by eyalbe4** [comment]
We're terribly sorry for the inconvenience caused by this!
We'll soon release a patch that permanently replaces the download URL.

**Comment by eyalbe4** [comment]
We've just released patch 1.1.2 with a fix for this issue.
Looking forward to your feedback.

**Comment by db250583** [comment]
I've tried to re-run some failing builds a few times without success.  Still receiving a 403 error when trying to use this action.  Working with internal teams to determine if there is something on our end additional needed.

**Comment by SherryChengAwsTacFuji** [comment]
@eyalbe4 Thank you for your quick response. I am seeing 'Unexpected HTTP response: 403' with default settings:

- name: Setup JFrog CLI
   uses: jfrog/setup-jfrog-cli@v1.1.2

**Comment by SherryChengAwsTacFuji** [comment]
Wonder if https://github.com/jfrog/setup-jfrog-cli/blob/33f2423da0cf326002e872aea2a1c4562418afb4/lib/utils.js#L65 also needs update, don't really know javascript, and sorry if not related.

**Comment by eyalbe4** [comment]
You're correct @SherryChengAwsTacFuji.
Give it a try now.
You can use 
```
uses: jfrog/setup-jfrog-cli@v1
```
Looking forward to your feedback.

**Comment by db250583** [comment]
Latest update seems ot have worked for my builds!  Thank you so much!

**Comment by eyalbe4** [comment]
Thanks for confirming @db250583.
All - please accept our apologies for the inconvinience caused by this incident!

**Comment by SherryChengAwsTacFuji** [comment]
Works for me too, appreciate the quick fix!
